project_id = "vjlkffoyvcqxmyhkhalv"

[functions.parse-resume]
verify_jwt = false

[functions.scrape-profile-url]
verify_jwt = false

[functions.contact-reply]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
